In [30]:
import numpy as np 
import pandas as pd
company=["HP","Lenovo","Asus","Dell"]
days=["Monday","Tuesday","Wednesday","Thursday","Friday"]
sales_data=np.array([
    [2,1,0,3,4],
    [3,4,5,0,2],
    [4,3,2,1,0],
    [1,0,3,4,2]
])
prices=[40000,45000,60000,35000]
sales_array=np.array(sales_data)
print(sales_array)
tcs=np.sum(sales_data,axis=1)
revenue=np.array(prices*tcs)
print(revenue)


[[2 1 0 3 4]
 [3 4 5 0 2]
 [4 3 2 1 0]
 [1 0 3 4 2]]
[400000 630000 600000 350000]


In [2]:
totalsale=np.array([np.sum(sales_data,axis=0)])
new_sales=np.concatenate((sales_data,totalsale),axis=0)
print(new_sales)

[[ 2  1  0  3  4]
 [ 3  4  5  0  2]
 [ 4  3  2  1  0]
 [ 1  0  3  4  2]
 [10  8 10  8  8]]


In [38]:
df=pd.DataFrame(sales_data)
a=df.sum(axis=1)
df["col"]=a*prices
print(df)




   0  1  2  3  4     col
0  2  1  0  3  4  400000
1  3  4  5  0  2  630000
2  4  3  2  1  0  600000
3  1  0  3  4  2  350000


In [46]:
p=pd.DataFrame(sales_data,index=company,columns=days)
p.iloc[:,3]=[3,434,232,4545]
p

Monday  Tuesday  Wednesday  Thursday  Friday
HP           2        1          0         3       4
Lenovo       3        4          5       434       2
Asus         4        3          2       232       0
Dell         1        0          3      4545       2

In [ ]:
sales_value=np.random.randint(6,size=(4,5))
p1=pd.DataFrame(sales_value,index=company,columns=days)

KeyError: 'H,mm'

In [ ]:
a1r=int(input("Enter rows in first matrix: "))
a1c=int(input("Enter columns in first matrix: "))
a2r=int(input("Enter rows in second matrix: "))
a2c=int(input("Enter columns in second matrix: "))
a1= np.random.randint(100,size=(a1r,a1c))
a2= np.random.randint(100,size=(a2r,a2c))
a11=a1[(a1%2==0) & (a1%4!=0)]
a22=a2[(a2%2==0) & (a2%3==0)]
print("a1:\n",a1)
print("a2:\n",a2)
print("a11:\n",a11)
print("a21:\n",a22)



a1:
 [[28 83 88  4]
 [89 73 74 46]
 [29 16 32 13]]
a2:
 [[71 77 34 42]
 [63 64 96 36]
 [35 26  1 79]
 [83 85  8 63]
 [29 81 59 19]]
a11:
 [74 46]
a21:
 [42 96 36]


In [16]:
print(a11.size==0)
print(a22.size==0)

False
False


In [9]:
import numpy as np
a1s=np.array(a1.flatten())
a2s=np.array(a2.flatten())
a3=np.concatenate(a1s,a2s)
a3

NameError: name 'a1' is not defined

In [2]:
import myModule as mm 
x=int(input("Enter Number"))
print(mm.myFact(x+1))



[1, 1, 2, 6, 24, 120]


In [ ]:
import numpy as np
def isprime(n):
    h=n//2
    while(h>1):
        if(n%h==0):
            return False
        h=h-1
    return True
a1=np.arange(32)
a2=[int(x) for x in a1 if(isprime(x))]
a3=[int(x) for x in a1 if(isprime(x)==0)]
print(a2)
print(len(a2))

print(a3)
a4=np.diag(a2)
a5=np.diag(a3)
print(a4)
print(a5)

[0, 1, 2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31]
13


AttributeError: 'list' object has no attribute 'size'

In [27]:
def f1(*args,**kwargs):
    return kwargs
print(f1(n1=290,hgh=299,hdsh=287))

{'n1': 290, 'hgh': 299, 'hdsh': 287}


In [12]:
int(np.floor(69**(1/2)))

8

In [7]:
x=int(input("Enter Range of integers"))
print(mm.myPsq(x))

[]
