In [2]:
import numpy as np 
import pandas as pd
company=["HP","Lenovo","Asus","Dell"]
days=["Monday","Tuesday","Wednesday","Thursday","Friday"]
sales_data=np.array([
    [2,1,0,3,4],
    [3,4,5,0,2],
    [4,3,2,1,0],
    [1,0,3,4,2]
])
prices=[40000,45000,60000,35000]
sales_array=np.array(sales_data)
print(sales_array)


[[2 1 0 3 4]
 [3 4 5 0 2]
 [4 3 2 1 0]
 [1 0 3 4 2]]


In [9]:
totalsale=np.array([np.sum(sales_data,axis=0)])
new_sales=np.concatenate((sales_data,totalsale),axis=0)
print(new_sales)

[[ 2  1  0  3  4]
 [ 3  4  5  0  2]
 [ 4  3  2  1  0]
 [ 1  0  3  4  2]
 [10  8 10  8  8]]


In [12]:
tcs=np.sum(sales_data,axis=1)
revenue=prices*tcs
print(revenue)

[400000 630000 600000 350000]


In [1]:
import pandas as pd
p=pd.DataFrame(index=company,columns=days)
print(p)

NameError: name 'company' is not defined

In [14]:
p=pd.DataFrame
p

TypeError: 'dict' object is not callable